### ISSUE TITLE
WEB!!!

### ISSUE THREAD

**Issue by MMAKENPO** [damienmauchamp/apple-music-new-releases#1]
HELLO BRO!!!TELL ME PLEASE WE CAN SEARCH SONGS AND ALBUMS FROM ITUNES?AND IF YES,PLEASE COULD YOU TELL ME THE WEB?

**Comment by damienmauchamp** [comment]
Hi, I’m just finishing some stuff first but  I will write a complete README file with all the explanations, setups and screenshots very soon.

I might also write an installation script to make this easier.

With this project, you’ll be able to retrieve all the albums and songs from artists of your choice.

**Comment by MMAKENPO** [comment]
MY FRIEND I AM NOT DEVELOPER AND I HAVE NO IDEA FROM PROGRAMMING!!!PLEAS COULD YOU MAKE ONE WEB?
